eureka.client.serviceUrl.defaultZone: http://${hostserver:localhost}:8761/eureka/

server:
  port: ${PORT:8761}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false